### ISSUE TITLE
Support GitHub workflow and deployment to GitHub Pages

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/react-static-plugin-aperis-doc-pages#3]

**Comment by ronaldtse** [comment]
Paneron alpha 19 / Aperis alpha 34 now drops CI workflow despite it being present before. Such as https://github.com/confium/confium.org/pull/1

**Comment by ronaldtse** [comment]
This issue is blocking confium.org deployment. @strogonoff can we can get it fixed up today? Thanks!

**Comment by ronaldtse** [comment]
e.g. we can have workflow files namespaced for Aperis/Paneron. e.g. .github/workflows/aperis_xxx.yml, and do not delete the existing workflow files not created by Aperis? People will want to have custom workflows depending on datasets.

**Comment by strogonoff** [comment]
This is an interesting idea. I suppose we could support both dataset-specific workflows (should be easier) as well as cross-dataset (repo-wide) workflows (more involved, can be done later).

**Comment by ronaldtse** [comment]
Agree.

**Comment by strogonoff** [comment]
Since an extension can not by design affect data outside the directory containing a dataset it manages, Paneron would have to provide a special hook for it to contribute a CI configuration. Tracking that in https://github.com/paneron/paneron/issues/17
